SELECT * FROM USER_INDEXES;
ALTER INDEX WEBSITE_PK REBUILD
TABLESPACE INDX;

/*Tablespace for UIAALUMNI01*/
CREATE TABLESPACE UIAALUMNI01 ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO;

ALTER USER UIAALUMNI quota 50M on UIAALUMNI01;

ALTER TABLE I_ACCOUNT MOVE
PCTFREE 15
STORAGE (INITIAL 4M NEXT 4M MAXSIZE 4M)
TABLESPACE UIAALUMNI01;

ALTER TABLE I_DONATION MOVE
PCTFREE 15
STORAGE (INITIAL 4M NEXT 4M MAXSIZE 4M)
TABLESPACE UIAALUMNI01;

ALTER TABLE I_WEBSITE MOVE
PCTFREE 15
STORAGE (INITIAL 4M NEXT 4M MAXSIZE 4M)
TABLESPACE UIAALUMNI01;

/*Tablespace for UIAALUMNI02*/
CREATE TABLESPACE UIAALUMNI02 ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO;

ALTER USER UIAALUMNI quota 50M on UIAALUMNI02;

ALTER TABLE I_DONATION_DETAIL MOVE
PCTFREE 5
STORAGE (INITIAL 2M NEXT 2M MAXSIZE 4M)
TABLESPACE UIAALUMNI02;

/*Tablespace for UIAALUMNI03*/
/*Tablespace for UIAALUMNI03 is calculated to
8M, but maximum allowed size is 4M according to the task.*/
CREATE TABLESPACE UIAALUMNI03 ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO;

ALTER USER UIAALUMNI quota 50M on UIAALUMNI03;

ALTER TABLE I_PROJECT MOVE
PCTFREE 10
STORAGE (INITIAL 4M NEXT 4M MAXSIZE 4M)
TABLESPACE UIAALUMNI03;

ALTER TABLE I_BILLING MOVE
PCTFREE 5
STORAGE (INITIAL 4M NEXT 4M MAXSIZE 4M)
TABLESPACE UIAALUMNI03;

/*Tablespace for UIAALUMNI04*/
CREATE TABLESPACE UIAALUMNI04 ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO;

ALTER USER UIAALUMNI quota 50M on UIAALUMNI04;

ALTER TABLE I_BUDGET MOVE
PCTFREE 5
STORAGE (INITIAL 64K NEXT 64K MAXSIZE 4M)
TABLESPACE UIAALUMNI04;

ALTER TABLE I_FOCUS_AREA MOVE
PCTFREE 30
STORAGE (INITIAL 64K NEXT 64K MAXSIZE 4M)
TABLESPACE UIAALUMNI04;

ALTER TABLE I_GIVING_LEVEL MOVE
PCTFREE 25
STORAGE (INITIAL 64K NEXT 64K MAXSIZE 4M)
TABLESPACE UIAALUMNI04;

ALTER TABLE I_PROJECT_TYPE MOVE
PCTFREE 30
STORAGE (INITIAL 64K NEXT 64K MAXSIZE 4M)
TABLESPACE UIAALUMNI04;

SELECT * FROM DBA_Tablespaces;
SELECT * FROM USER_Indexes;